Repository jenkinsci/global-build-stats-plugin, pull requests merged in 2023-08, with the labels that each got.

#50 Test on Java 21
  Jenkinsfile
Labels: chore

#49 [JENKINS-71677] Remove usages of Prototype
  src/main/resources/hudson/plugins/global_build_stats/GlobalBuildStatsPlugin/buildHistory.jelly
  src/main/resources/hudson/plugins/global_build_stats/GlobalBuildStatsPlugin/index.jelly
  src/main/resources/hudson/plugins/global_build_stats/GlobalBuildStatsPlugin/retentionStrategies/discardResultsOlderThanDays.jelly
  src/main/webapp/scripts/global-build-stats/BuildStatConfigForm.js
  src/main/webapp/scripts/global-build-stats/BuildStatConfigs.js
  src/main/webapp/scripts/global-build-stats/buildHistory.js
  src/main/webapp/scripts/global-build-stats/chartList.js
  src/main/webapp/scripts/global-build-stats/standardFunctions.js
Labels: developer

#53 Added README.md from the wiki article
  README.md
  docs/images/GlobalBuildStats - BuildSearchEngine.png
  docs/images/GlobalBuildStats - ChartCreation.png
  docs/images/GlobalBuildStats - Last15Weeks.png
  docs/images/GlobalBuildStats - Last30Days.png
  docs/images/GlobalBuildStats-MainScreen - Init.png
  docs/images/configuringRetentionStrategies.png
  docs/images/gbs-identifier.png
  docs/rest_api.md
Labels: chore, skip-changelog

#54 Switch the plugin documentation to github
  pom.xml
Labels: chore, skip-changelog

#56 Reduce Jenkinsfile diffs to archetype
  Jenkinsfile
Labels: chore
